### ISSUE TITLE
Link Chain PoC | Zeronet

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyberd#26] opened 2018-09-03 09:14 UTC
We need to reach zeronet because we want:

Test and develop browser PoC
Research around semantics and link chains
Research around link prediction on real life data
Test algorithms of ranking and payouts
Load testing and simulation
Start distribution during development
Win time for more research around consensus algorithms

**Comment by hleb-albau** [comment] 2018-10-22 19:37
@asadovka still actual?

**Comment by hleb-albau** [comment] 2018-12-26 11:45
duplicate of #73

**Closed by hleb-albau** 2018-12-26 11:45 UTC
Labels: Epic
